
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.provider :virtualbox do |vb|
		vb.gui = false
		vb.customize ["modifyvm", :id, "--memory", "4048"]
	end

	config.vm.define :master do |master|
		master.ssh.forward_x11 = true
		master.vm.box      = 'packer'
		master.vm.hostname = 'local.puppetmaster'
		master.vm.synced_folder './files', '/vagrant_data'
		master.vm.synced_folder './puppet/modules', '/puppet_modules'
		master.vm.synced_folder './puppet/manifests', '/puppet_manifests'
		master.vm.network   :private_network, ip: '10.10.11.10'
		master.vm.provision :shell, :path => 'bootstrap-master.sh'
	end
end
